dynaconf_merge: true
default:
  env:

  # MongoDB
  database: cron5
  workflow_collection: workflow
  connections_collection: connections
  platform_tokens: platform_tokens
  facebook_fields: facebook_fields
  google_fields: google_fields
  tiktok_fields: tiktok_fields
  execution_history_collection: execution_history

  mongo_uri:
  mongo_port:
  mongo_username:
  mongo_password:
  mongo_database: cron5

  # Request Configuration (global)
  max_workers: 50
  timestamp_format: '%Y%m%d%H%M%S'

  # temp directory
  temp_dir: /tmp

  # Google Cloud
  google_cloud_project_id: cron5-dev

  # Pub/Sub Tracking
  enable_tracking: true
  pubsub_topic_id: workflow-status-events
  pubsub_subscription_id: workflow-status-sub
